change mount_device to mount_device2 to allow options to be set start to add chroot option (to prepare chroot in the device)

diff --git a/blk b/blk
--- a/blk
+++ b/blk
@@ -33,6 +33,7 @@ cat << FIN
 Manage local FS devices
 Wihtout arg display dev + label and exit
 usage : $PRGNAME 
+	-C : chroot the given partition
         -d : run in debug mode
 	-l : Display linux type only (ext4) 	
 	-m : mount all devices ext4 to /media/\$LABEL (create if not exist)
@@ -57,8 +58,96 @@ fi
         exit $RET
 }
 
+amiroot() {
+CMD=/usr/bin/whoami
+if [ ! -x $CMD ];
+then
+        printf "%-10s %-10s %-22s %-30s \n" "ERROR :" "check root : "  "cant get root status"
+        return 1
+else
+        __DUM=$(eval $CMD)
+        if [ ${__DUM:=NULL} != "root" ];
+        then
+                printf "%-10s %-10s %-22s %-30s \n" "ERROR :" "check root : " "Need to be root to run this"
+                return 1
+        fi
+fi
+return 0
+}
+
 function rundiag() {
 echo > /dev/null
+}
+
+get_valid_devname() { 
+local __ARG1
+local __DEV
+__ARG1=$1
+__DEV=$(blkid -L $CHROOT)
+if [ $? -ne 0 ] ;
+then 
+	printf "%-10s %-10s %-22s %-30s \n" "ERROR :" "get_valid_devname" "$__ARG1 is not existing"
+	return 1 
+else
+	echo "$__DEV"
+	return 0
+fi
+}
+
+# need to have DEV to mount from blkid and mount point 
+# optionnal -C to then chroot in the device
+mount_device2() {
+if ! amiroot ; then return 9 
+fi
+OPTION=NONE
+[[ ${ZDEBUG:=0} -eq 1 ]] && echo "A $# : Arg $* : I $OPTIND A $OPTARG" 
+while getopts C sarg
+do
+[[ ${ZDEBUG:=0} -eq 1 ]] && echo "arg $sarg"
+case $sarg in
+        C)      [[ ${ZDEBUG:=0} -eq 1 ]] && echo "Boucle chroot" 
+		OPTION=CHROOT ;;
+        *)      printf "%-10s %-10s %-22s %-30s \n" "ERROR :" "mount_device2 : " "Error in passing arguments"
+                usage
+                end ;;
+esac
+done
+
+shift $(( $OPTIND - 1))
+
+if [ $# -ne 2 ] ;
+then
+        printf "%-10s %-10s %-22s %-30s \n" "ERROR :" "mount_device2 : " "Arg not OK  $#"
+	return 1
+fi
+
+DEV=$1
+LABEL=$2
+DUMMY=$(df -t ext4 | grep -w $DEV  | awk '{print $NF}')
+NBCHAR=$(echo $DUMMY | wc -c)
+if [ $NBCHAR -eq 1 ] ;
+then
+        if [ ! -d /mnt/$LABEL ] ;
+        then
+                mkdir /mnt/$LABEL
+                if [ $? -ne 0 ] ;
+                then
+                        printf "%-10s %-10s %-22s %-30s \n" "ERROR :" "mount_device2 : " "Error bulding  /mnt/$LABEL"
+                        return
+                fi
+        fi
+        printf "%-10s %-10s %-22s %-30s \n" "INFO :" "mount_device2 : " "Mounting $DEV on /mnt/$LABEL"
+        mount $DEV /mnt/$LABEL
+else
+        printf "%-10s %-10s %-22s %-30s \n" "INFO :" "mount_device2 : " "$DEV already mounted on $DUMMY"
+
+fi
+case $OPTION in 
+	CHROOT) [[ ${VERBOSE:=0} -eq 1 ]] && echo "mount chroot  $*" ;;
+	NONE) [[ ${VERBOSE:=0} -eq 1 ]] && echo "mount normal  $*" ;; 	
+	*) printf "%-10s %-10s %-22s %-30s \n" "ERROR :" "mount_device2 : " "Error in running option arguments"
+esac
+
 }
 
 mount_device() {
@@ -116,10 +205,14 @@ TYPE="NONE"
 MOUNT=0
 SINGLE=__NONE__
 LABEL=ext4
+CHROOT=__NONE__
+ZDEBUG=0
+VERBOSE=0
 
-while getopts dhlmps:u sarg
+while getopts C:dhlmps:uvZ sarg
 do
 case $sarg in
+	C)	CHROOT=$OPTARG ;;
         d)      set -x
         	DEBUG=1 ;;
         h)      usage
@@ -136,20 +229,33 @@ case $sarg in
 	u)	umount_all
 		exit
 		;;
+	v)	VERBOSE=1 ;;
+	Z)	ZDEBUG=1 ;;
         *)      echo "ERROR : $PRGNAME : Bad option or misusage"
                 usage
                 end ;;
 esac
 done
 
+OPTIND=1
 COMMAND="blkid" 
 
+
+
+if [ ${CHROOT:=__NONE__} != "__NONE__" ];
+then
+	#DEV=$(blkid -L $CHROOT)
+	DEV=$(get_valid_devname $CHROOT)
+	[[ $? -ne 0 ]] && end $?
+	mount_device2 -C $DEV $CHROOT
+	end
+fi
 
 if [ "A$SINGLE" != "A__NONE__" ] ;
 then
 	DEV=$(blkid -L $SINGLE)
-	mount_device $DEV $SINGLE  
-	exit
+	mount_device2 $DEV $SINGLE  
+	end
 fi
 
 if [ $TYPE == "linux" ] ;
